spring.datasource.platform=d6j6nb8r8qhi39
spring.datasource.url=jdbc:postgresql://ec2-99-80-200-225.eu-west-1.compute.amazonaws.com:5432/d6j6nb8r8qhi39?user=hmonatrdunbmsk&password=bc8655f5f5d093354135302b6d886abf774ded7840a6fe4648605b109028a30d
spring.datasource.username=hmonatrdunbmsk
spring.datasource.password=bc8655f5f5d093354135302b6d886abf774ded7840a6fe4648605b109028a30d


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true



spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.continue-on-error=true
